LOAD DATA INFILE"C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/episode.csv" INTO TABLE TEMPEPISODES FIELDS TERMINATED BY "|" LINES TERMINATED BY "\n" IGNORE 1 ROWS;

LOAD DATA INFILE"C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/movie.csv" INTO TABLE TEMPMOVIES FIELDS TERMINATED BY "|" LINES TERMINATED BY "\n" IGNORE 1 ROWS;

LOAD DATA INFILE"C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/series.csv" INTO TABLE TEMPSERIES FIELDS TERMINATED BY "|" LINES TERMINATED BY "\n"IGNORE 1 ROWS;

LOAD DATA INFILE"C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/actors.csv" INTO TABLE TEMPACTORS FIELDS TERMINATED BY "|" LINES TERMINATED BY "\n"IGNORE 1 ROWS;

LOAD DATA INFILE"C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/actresses.csv" INTO TABLE TEMPACTRESSES FIELDS TERMINATED BY "|" LINES TERMINATED BY "\n"IGNORE 1 ROWS;

LOAD DATA INFILE"C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/location.csv" INTO TABLE TEMPLOCATION FIELDS TERMINATED BY "|" LINES TERMINATED BY "\n"IGNORE 1 ROWS;

LOAD DATA INFILE"C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/genre.csv" INTO TABLE TEMPGENRE FIELDS TERMINATED BY "|" LINES TERMINATED BY "\n"IGNORE 1 ROWS;

LOAD DATA INFILE"C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/movieruntime.csv" INTO TABLE TEMPMOVIERUNTIME FIELDS TERMINATED BY "|" LINES TERMINATED BY "\n"IGNORE 1 ROWS;

LOAD DATA INFILE"C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/seriesruntime.csv" INTO TABLE TEMPSERIESRUNTIME FIELDS TERMINATED BY "|" LINES TERMINATED BY "\n"IGNORE 1 ROWS;

LOAD DATA INFILE"C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/episodesruntime.csv" INTO TABLE TEMPEPISODERUNTIME FIELDS TERMINATED BY "|" LINES TERMINATED BY "\n"IGNORE 1 ROWS;

LOAD DATA INFILE"C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/soundtrackmovie.csv" INTO TABLE TEMPSOUNDTRACKMOVIES FIELDS TERMINATED BY "|" LINES TERMINATED BY "\n"IGNORE 1 ROWS;

LOAD DATA INFILE"C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/soundtrackseries.csv" INTO TABLE TEMPSOUNDTRACKSERIES FIELDS TERMINATED BY "|" LINES TERMINATED BY "\n"IGNORE 1 ROWS;

LOAD DATA INFILE"C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/directors.csv" INTO TABLE TEMPDIRECTORS FIELDS TERMINATED BY "|" LINES TERMINATED BY "\n"IGNORE 1 ROWS;